# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d75bc9e33720a88764de60b7add062e3d9b9c3221e9397baf4f46dee3632d581fc93ec83bad65c1f8c10a053f5a96d5b8fc101b89ac3a11a5e1ff6603f28f48

test:
  secret_key_base: ee03f6526e678669674c6820264698b2b346878589452513962c82747b9e4e427ac5d9e785f30d29b29ee1ba3a847f9880695a3d3e495c510efbdef7315e2de9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
